"""Stable public error/control codes for backend v0.1."""

from enum import StrEnum


class StableCode(StrEnum):
    E_REGISTRY_READ = "E_REGISTRY_READ"
    E_REGISTRY_DENY = "E_REGISTRY_DENY"
    E_ASSET_NOT_ALLOWLISTED = "E_ASSET_NOT_ALLOWLISTED"
    E_FETCH_INTEGRITY = "E_FETCH_INTEGRITY"
    E_FINGERPRINT_INVALID = "E_FINGERPRINT_INVALID"
    N_NO_CHANGE = "N_NO_CHANGE"
    E_EXTRACTION_INCOMPLETE = "E_EXTRACTION_INCOMPLETE"
    E_CONTENT_BOUNDARY = "E_CONTENT_BOUNDARY"
    E_ASSET_URL_MAP = "E_ASSET_URL_MAP"
    E_CHUNK_CONTRACT = "E_CHUNK_CONTRACT"
    E_ACCESS_POLICY = "E_ACCESS_POLICY"
    E_INDEX_COVERAGE = "E_INDEX_COVERAGE"
    E_PUBLISH_PRECONDITION = "E_PUBLISH_PRECONDITION"
    E_DB_TRANSACTION = "E_DB_TRANSACTION"
    E_POST_PUBLISH_SMOKE = "E_POST_PUBLISH_SMOKE"
    E_RESTORE_REQUIRED = "E_RESTORE_REQUIRED"
    E_AUDIT_INCOMPLETE = "E_AUDIT_INCOMPLETE"
    E_RETRIEVAL_UNAVAILABLE = "E_RETRIEVAL_UNAVAILABLE"
    E_PROVENANCE_BROKEN = "E_PROVENANCE_BROKEN"
    E_CONFIG_INVALID = "E_CONFIG_INVALID"
